import type { ChatSession } from '../typings/types'

export const chatSessionsData: ChatSession[] = [
    {
        id: 'session-1',
        topic: '雪碧',
        statistic: {
            chatCount: 2,
            tokenCount: 50,
            wordCount: 30,
        },
        messages: [
            {
                id: 'msg-1',
                content: '你好，给我拿一瓶雪碧。',
                role: 'user',
                session: undefined as any, // 避免循环引用
                validStatus: 'VALID',
                updatedAt: '2025-09-06T10:00:00Z',
                createdAt: '2025-09-06T10:00:00Z',
            },
            {
                id: 'msg-2',
                content: '好的，我将给你一瓶雪碧。',
                role: 'assistant',
                session: undefined as any,
                validStatus: 'VALID',
                updatedAt: '2025-09-06T10:00:05Z',
                createdAt: '2025-09-06T10:00:05Z',
            },
        ],
        createdBy: {
            id: 'user-1',
            avatar: '/avatars/user1.png',
            nickname: '小明',
            username: 'xiaoming',
            password: 'password1',
            updatedAt: '2025-09-06T09:00:00Z',
            createdAt: '2025-09-06T09:00:00Z',
            validStatus: 'VALID',
        },
        validStatus: 'VALID',
        updatedAt: '2025-09-06T10:00:05Z',
        createdAt: '2025-09-06T10:00:00Z',
    },
    {
        id: 'session-2',
        topic: '可乐',
        statistic: {
            chatCount: 3,
            tokenCount: 70,
            wordCount: 40,
        },
        messages: [
            {
                id: 'msg-3',
                content: '我要一瓶可乐',
                role: 'user',
                session: undefined as any,
                validStatus: 'VALID',
                updatedAt: '2025-09-06T11:00:00Z',
                createdAt: '2025-09-06T11:00:00Z',
            },
            {
                id: 'msg-4',
                content: '好的，我将给你一瓶可乐',
                role: 'assistant',
                session: undefined as any,
                validStatus: 'VALID',
                updatedAt: '2025-09-06T11:00:02Z',
                createdAt: '2025-09-06T11:00:02Z',
            },
            {
                id: 'msg-5',
                content: '谢谢！',
                role: 'user',
                session: undefined as any,
                validStatus: 'VALID',
                updatedAt: '2025-09-06T11:00:05Z',
                createdAt: '2025-09-06T11:00:05Z',
            },
        ],
        createdBy: {
            id: 'user-2',
            avatar: '/avatars/user2.png',
            nickname: '小红',
            username: 'xiaohong',
            password: 'password2',
            updatedAt: '2025-09-06T09:30:00Z',
            createdAt: '2025-09-06T09:30:00Z',
            validStatus: 'VALID',
        },
        validStatus: 'VALID',
        updatedAt: '2025-09-06T11:00:05Z',
        createdAt: '2025-09-06T11:00:00Z',
    },
    {
        id: 'session-3',
        topic: '芬达',
        statistic: {
            chatCount: 2,
            tokenCount: 60,
            wordCount: 35,
        },
        messages: [
            {
                id: 'msg-6',
                content: '给我一瓶芬达',
                role: 'user',
                session: undefined as any,
                validStatus: 'VALID',
                updatedAt: '2025-09-06T12:00:00Z',
                createdAt: '2025-09-06T12:00:00Z',
            },
            {
                id: 'msg-7',
                content: '好的，我将给你一瓶芬达',
                role: 'assistant',
                session: undefined as any,
                validStatus: 'VALID',
                updatedAt: '2025-09-06T12:00:03Z',
                createdAt: '2025-09-06T12:00:03Z',
            },
        ],
        createdBy: {
            id: 'user-3',
            avatar: '/avatars/user3.png',
            nickname: '小刚',
            username: 'xiaogang',
            password: 'password3',
            updatedAt: '2025-09-06T10:00:00Z',
            createdAt: '2025-09-06T10:00:00Z',
            validStatus: 'VALID',
        },
        validStatus: 'VALID',
        updatedAt: '2025-09-06T12:00:03Z',
        createdAt: '2025-09-06T12:00:00Z',
    },
]
